### ISSUE TITLE
Error on make

### ISSUE THREAD

**Issue by schmeing** [Christina-hshi/SH-assembly#5]
Hi,
I get the following error on make:
```
In file included from /home/cluster/sschme/software/SH-assembly/core/unitig_graph.cpp:13:0:
/home/cluster/sschme/software/SH-assembly/core/unitig_graph.h: At global scope:
/home/cluster/sschme/software/SH-assembly/core/unitig_graph.h:76:10: error: ‘tbb_hash’ is not a class template
   struct tbb_hash<DNAString>
          ^
/home/cluster/sschme/software/SH-assembly/core/unitig_graph.h:77:3: error: explicit specialization of non-template ‘tbb::tbb_hash’
   { 
   ^
core/CMakeFiles/core-objs.dir/build.make:62: recipe for target 'core/CMakeFiles/core-objs.dir/unitig_graph.cpp.o' failed
make[2]: *** [core/CMakeFiles/core-objs.dir/unitig_graph.cpp.o] Error 1
```

The tbb_hash was deprecated (and probably by now removed) based on this:
https://software.intel.com/content/www/us/en/develop/documentation/tbb-documentation/top/intel-threading-building-blocks-developer-reference/appendices/deprecated-features/obsolete-c-functionality/tbbhash-class.html

I am using version "oneapi-tbb-2021.3.0".

Thx and best,
Stephan

**Comment by Christina-hshi** [comment]
Thanks! Stephan!
SH-assembly was tested with tbb version `2019.7`, which can be installed using conda.
`conda install -c conda-forge tbb=2019.7`

I have updated the README.

**Comment by schmeing** [comment]
It also works with version 2020.3, where it is deprecated, but not removed, yet.

**Comment by Christina-hshi** [comment]
Thanks, Stephan! I have added this version in the README.
